# Source: gitlab-argo-bridge/templates/build.yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: gitlab-argo-bridge
  name: gitlab-argo-bridge
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: gitlab-argo-bridge:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/redhat-cop/tool-integrations.git
      ref: master
    type: Git
    contextDir: "/argo-cd-bridges/gitlab"
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0