apiVersion: v1
stringData:
  GITLAB_API_URL: "{{ .Values.gitLab.apiUrl }}"
  GITLAB_PERSONAL_ACCESS_TOKEN: "{{ .Values.gitLab.personalAccessToken }}"
  RESIDENCIES_PARENT_REPOSITORIES_ID: "{{ .Values.gitLab.parentRepositoryID }}"
kind: Secret
metadata:
  name: {{ include "launcher.fullname" . }}
type: Opaque
