{{- if .Values.setupClusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}