apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ include "app.fullname" . }}
  name: {{ include "app.fullname" . }}
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: "{{ .Values.imageName }}:{{ .Values.imageTag }}"
    importPolicy:
      scheduled: true
    name: {{ .Values.imageTag }}
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
