apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ include "app.fullname" . }}
  name: {{ include "app.fullname" . }}
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: ""
